
# DELETE   http://localhost:5432/conceptos/3 HTTP/1.1
# Content-Type: application/json

DELETE      http://localhost:5432/clientes/2 HTTP/1.1
Content-Type: application/json

{
  "cuit": "20322239788",
  "razon_social": "Susana Rascanuca",
  "email": "SusanaRascanucaBlonde@gmail.com",
  "telefono": 46599865,
  "celular": 1564875421,
  "direccion": "Rivadavia 1823"
}

#  {
#    "id": 3,
#    "idTipo": 3,
#    "descripcion": "Internet",
#    "importe": 800
#  }

# ##
# GET   http://localhost:5432/clientes HTTP/1.1
# content-type: application/json




